---
title: "About me"
output: 
  html_document:
    toc: true
    toc_float: true
   
---

# Personal information 
Zixuan Qiu

zq2227@cumc.columbia.edu | Zx.qiu2022@gmail.com | (352) 999-9571

## EDUCATION                                                                                                                                                                                     
### Columbia University Mailman school of public health, NY   08/2023 – 12/2025  

•	MS in Biostatistics-Theory and Method.                                                                                                

### University of Florida, Gainesville, FL	08/2018 – 12/2022

•	BS in Biotechnology - Bioinformatics. GPA 3.64/4.00





## INTERNSHIP EXPERIENCE                                                                                                                                                             .
### JSBioscience, Lanzhou, China	05/2021– 07/2021	
**Lab & QA Technician**

•	Worked part-time on biological BSL-3 in assisting the testing process and collecting test records.  Assisted senior technician in finishing quality tests for serum-free medium and processed test records. Learned the knowledge about sterile techniques and sample preparation and storage. 

•	Learned and used R-studio to process daily quality reports; joined the team in writing and revision of SOP for a new biological production plant.




### Chinese Academy of Sciences, Lanzhou, China 	09/2021- 10/2021
Advisor: Professor Qingguo Zhou
•	Used Python to provide descriptive statistics support; learned how to apply modeling and other statistical methods to analyze biodiversity richness in a region. Also provided R tutorial help to lab members.

